<?php

/**
 * @file
 * Drupal Module: Bootstrap Basic Image Gallery.
 *
 * Image formatter for displaying as bootstrap-based image gallery.
 */

/**
 * Implements hook_theme().
 */
function bootstrap_basic_image_gallery_theme($existing, $type, $theme, $path) {
  return [
    'bootstrap_basic_image_gallery' => [
      'variables' => [
        'main' => [],
        'thumbnails' => [
          'class' => NULL,
          'images' => [],
        ],
        'lazyload' => NULL,
        'modal' => [
          'id' => NULL,
        ],
        'carousel' => [
          'id' => NULL,
          'autoplay' => NULL,
          'interval' => 5000,
          'images' => [],
        ],
      ],
    ],
  ];
}
